//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleFinance_Data
    {
        public long Identity { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Range_From { get; set; }
        public Nullable<decimal> Range_To { get; set; }
        public Nullable<decimal> C52_Weeks_From { get; set; }
        public Nullable<decimal> C52_Weeks_To { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> Vol_M_ { get; set; }
        public Nullable<decimal> Avg_M_ { get; set; }
        public Nullable<decimal> Mkt_Cap_B_ { get; set; }
        public Nullable<decimal> P_E { get; set; }
        public Nullable<decimal> Div { get; set; }
        public Nullable<decimal> Yield { get; set; }
        public Nullable<decimal> EPS { get; set; }
        public Nullable<decimal> Shares_B_ { get; set; }
        public string Beta { get; set; }
        public Nullable<long> S_P_ASX_200 { get; set; }
        public string Group { get; set; }
    }
}
