//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleFinance_News
    {
        public long Identity { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public System.DateTime Date { get; set; }
        public string Website { get; set; }
        public string Author { get; set; }
        public string Story { get; set; }
        public Nullable<long> NegWords { get; set; }
        public Nullable<long> PosWords { get; set; }
        public Nullable<long> Length_of_Post { get; set; }
        public string Group { get; set; }
    }
}
